### ISSUE TITLE
Plugin conflicting with another push enabled plugin 

### ISSUE THREAD

**Issue by sisodiakaran** [smooch/smooch-cordova#30]
Build is failing with following error:

```
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/actions/ItemListIntents;

        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:579)
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:535)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:517)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:164)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:504)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
        at com.android.dx.command.dexer.Main.run(Main.java:277)
        at com.android.dx.command.dexer.Main.main(Main.java:245)
        at com.android.dx.command.Main.main(Main.java:106)



 FAILED



FAILURE: Build failed with an exception.


* What went wrong:
Execution failed for task ':transformClassesWithDexForDebug'.

> 
com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/home/karan/jdk1.8.0_91/bin/java'' finished with non-zero exit value 2
```

Please suggest me some work around for this situation.

Thanks

**Comment by sisodiakaran** [comment]
Any clue?

**Comment by jugarrit** [comment]
Not really sure how to address this.
We will be updating for FCM shortly, hopefully it will solve the issue by itself.

**Comment by jugarrit** [comment]
Please try the latest version of the plugin and open this again if the problem persists.
