### ISSUE TITLE
android take picture problem

### ISSUE THREAD

**Issue by olioldev** [smooch/smooch-cordova#32]
Hi
Sorry for my English.
I have a simple cordova app with smooch plugin and whitelist, when I want generate apk, I get this error:

> Error:Execution failed for task ':processDebugResources'.
> Error: more than one library with package name 'com.google.android.gms'
## So I change my smooch gradle:

repositories {
       jcenter()
 }

   buildscript {
       repositories {
           jcenter()
    }

 dependencies {
        //classpath 'com.google.gms:google-services:1.3.0-beta1'
  }
}

dependencies {
    //compile 'com.google.android.gms:play-services-gcm:7.5.0'
    compile 'com.google.code.gson:gson:2.3.1'
    compile 'com.squareup.okhttp:okhttp:2.4.0'
    compile 'io.smooch:core:latest.release'
    compile 'io.smooch:ui:latest.release'
}

Know I can generate apk, but when I want take picture from camera I get "unfortunately" and log is:

---

java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.contains(java.lang.CharSequence)' on a null object reference
            at io.smooch.ui.fragment.ConversationFragment.dispatchTakePhotoIntent(Unknown Source)
            at io.smooch.ui.fragment.ConversationFragment.access$2300(Unknown Source)
            at io.smooch.ui.fragment.ConversationFragment$6.onClick(Unknown Source)
            at com.android.internal.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1082)
            at android.widget.AdapterView.performItemClick(AdapterView.java:305)
            at android.widget.AbsListView.performItemClick(AbsListView.java:1146)
            at android.widget.AbsListView$PerformClick.run(AbsListView.java:3057)
            at android.widget.AbsListView$3.run(AbsListView.java:3864)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:211)
            at android.app.ActivityThread.main(ActivityThread.java:5389)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
##             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)

Another options not worked fine like "Choose from Library", but "Use Last Photo Taken" worked fine.

Please let me what can I do?

Regards

**Comment by jugarrit** [comment]
I'll see what I can do.

**Comment by jugarrit** [comment]
I neglected to update the npm repo with the latest changes before, please update the plugin completely and try again.

Remove these lines:

```
//compile 'com.google.android.gms:play-services-gcm:7.5.0'
compile 'com.google.code.gson:gson:2.3.1'
compile 'com.squareup.okhttp:okhttp:2.4.0'
```

And if you want FCM in your application, change this one
`//classpath 'com.google.gms:google-services:1.3.0-beta1'`

To this:

`classpath 'com.google.gms:google-services:3.0.0'`

And add the following to the _bottom_ of the file:

`apply plugin: 'com.google.gms.google-services'`

**Comment by olioldev** [comment]
Thank you so much :)
I updated the plugin and my first problem solved :+1: 
my gradle:
repositories {
    jcenter()
}
dependencies {
    compile 'io.smooch:core:latest.release'
    compile 'io.smooch:ui:latest.release'
}

but my second problem had not solved :(

## I get this error when I want select image from album:

E/AndroidRuntime﹕ FATAL EXCEPTION: AsyncTask #5
    Process: ir.appeto.smooch, PID: 26219
    java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
            at io.smooch.ui.fragment.ConversationFragment.scaleBitmap(Unknown Source)
            at io.smooch.ui.fragment.ConversationFragment.smartDecode(Unknown Source)
            at io.smooch.ui.fragment.ConversationFragment.access$1100(Unknown Source)
            at io.smooch.ui.fragment.ConversationFragment$17.run(Unknown Source)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)

##             at java.lang.Thread.run(Thread.java:818)

or for take photo from camera I get this error:

---

PID: 31978
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.contains(java.lang.CharSequence)' on a null object reference
            at io.smooch.ui.fragment.ConversationFragment.dispatchTakePhotoIntent(Unknown Source)
            at io.smooch.ui.fragment.ConversationFragment.access$2300(Unknown Source)
            at io.smooch.ui.fragment.ConversationFragment$6.onClick(Unknown Source)
            at com.android.internal.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1082)
            at android.widget.AdapterView.performItemClick(AdapterView.java:305)
            at android.widget.AbsListView.performItemClick(AbsListView.java:1146)
            at android.widget.AbsListView$PerformClick.run(AbsListView.java:3057)
            at android.widget.AbsListView$3.run(AbsListView.java:3864)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:211)
            at android.app.ActivityThread.main(ActivityThread.java:5389)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)

##             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)

Can I remove send picture from ui?

Thank you
