### ISSUE TITLE
Failed to install with Cordova 9.x

### ISSUE THREAD

**Issue by milhouse1337** [smooch/smooch-cordova#42]
I just tried to install the plugin on a fresh cordova project and it failed.

Here is the steps.

```
cordova create test-project com.example.test "Test App"
cd test-project
cordova platform add ios
cordova platform add android
cordova plugin add smooch-cordova
```

Here is the error output.

```
Installing "cordova-plugin-smooch" for android
Subproject Path: CordovaLib
Subproject Path: app
Failed to install 'cordova-plugin-smooch': CordovaError: Using "requireCordovaModule" to load non-cordova module "fs" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.
    at Context.requireCordovaModule (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/Context.js:57:15)
    at module.exports (/Users/pascal/Vagrant/_cordova/gpsh/plugins/cordova-plugin-smooch/scripts/afterInstall.js:5:20)
    at runScriptViaModuleLoader (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:181:32)
    at runScript (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:157:16)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:125:20
    at process._tickCallback (internal/process/next_tick.js:68:7)
Using "requireCordovaModule" to load non-cordova module "fs" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.
```

Thank you!

**Comment by Morgan-LC** [comment]
### smooch-cordova/scripts/afterInstall.js  ...beforeUninstall.js:
You can replace : 
<pre>
<code>
var fs = context.requireCordovaModule('fs'),  
    path = context.requireCordovaModule('path');
</pre>
</code>
by
<pre>
<code>
var fs = require('fs'),  
    path = require('path');
</pre>
</code>
